name: "XY's Blog"
description: "Like a digital garden."

avatar: https://pianfan.github.io/images/avatar.png
favicon: https://pianfan.github.io/images/favicon.ico

# 用户主页仓库，不需要 baseurl
baseurl: ""

navigation:
  - name: 首页
    url: /
  - name: 画廊
    url: /gallery/
  - name: 关于
    url: /about
  - name: 分类
    url: /tags

paginate: 8

excerpt_separator: <!-- more -->

footer-links:
  zhihu: 3070_homepage
  email: xy053070@gmail.com
  facebook:
  github: XY3070
  rss:
  twitter: 
  youtube:

footer-text: Copyright (c) 2024 XY

url: https://XY3070.github.io

# ⚠️ 删除了全局 permalink: /:title/
# 避免覆盖 collections 的 permalink 规则

paginate_path: /page:num/

# The release of Jekyll Now
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

collections:
  gallery_albums:
    output: true
    permalink: /gallery/:name/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - GALLERY_STRUCTURE.md
